export default [
    {
        "login": "YashSampat23154",
        "id": 52824246,
        "node_id": "MDQ6VXNlcjUyODI0MjQ2",
        "avatar_url": "https://avatars.githubusercontent.com/u/52824246?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/YashSampat23154",
        "html_url": "https://github.com/YashSampat23154",
        "followers_url": "https://api.github.com/users/YashSampat23154/followers",
        "following_url": "https://api.github.com/users/YashSampat23154/following{/other_user}",
        "gists_url": "https://api.github.com/users/YashSampat23154/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/YashSampat23154/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/YashSampat23154/subscriptions",
        "organizations_url": "https://api.github.com/users/YashSampat23154/orgs",
        "repos_url": "https://api.github.com/users/YashSampat23154/repos",
        "events_url": "https://api.github.com/users/YashSampat23154/events{/privacy}",
        "received_events_url": "https://api.github.com/users/YashSampat23154/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "Prathamesh247",
        "id": 61054792,
        "node_id": "MDQ6VXNlcjYxMDU0Nzky",
        "avatar_url": "https://avatars.githubusercontent.com/u/61054792?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Prathamesh247",
        "html_url": "https://github.com/Prathamesh247",
        "followers_url": "https://api.github.com/users/Prathamesh247/followers",
        "following_url": "https://api.github.com/users/Prathamesh247/following{/other_user}",
        "gists_url": "https://api.github.com/users/Prathamesh247/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Prathamesh247/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Prathamesh247/subscriptions",
        "organizations_url": "https://api.github.com/users/Prathamesh247/orgs",
        "repos_url": "https://api.github.com/users/Prathamesh247/repos",
        "events_url": "https://api.github.com/users/Prathamesh247/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Prathamesh247/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "grey-hat2003",
        "id": 62413157,
        "node_id": "MDQ6VXNlcjYyNDEzMTU3",
        "avatar_url": "https://avatars.githubusercontent.com/u/62413157?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/grey-hat2003",
        "html_url": "https://github.com/grey-hat2003",
        "followers_url": "https://api.github.com/users/grey-hat2003/followers",
        "following_url": "https://api.github.com/users/grey-hat2003/following{/other_user}",
        "gists_url": "https://api.github.com/users/grey-hat2003/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/grey-hat2003/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/grey-hat2003/subscriptions",
        "organizations_url": "https://api.github.com/users/grey-hat2003/orgs",
        "repos_url": "https://api.github.com/users/grey-hat2003/repos",
        "events_url": "https://api.github.com/users/grey-hat2003/events{/privacy}",
        "received_events_url": "https://api.github.com/users/grey-hat2003/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "Vng12",
        "id": 69852996,
        "node_id": "MDQ6VXNlcjY5ODUyOTk2",
        "avatar_url": "https://avatars.githubusercontent.com/u/69852996?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Vng12",
        "html_url": "https://github.com/Vng12",
        "followers_url": "https://api.github.com/users/Vng12/followers",
        "following_url": "https://api.github.com/users/Vng12/following{/other_user}",
        "gists_url": "https://api.github.com/users/Vng12/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Vng12/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Vng12/subscriptions",
        "organizations_url": "https://api.github.com/users/Vng12/orgs",
        "repos_url": "https://api.github.com/users/Vng12/repos",
        "events_url": "https://api.github.com/users/Vng12/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Vng12/received_events",
        "type": "User",
        "site_admin": false
    }
]