export default {
    login: "kshitizJ",
    id: 53303745,
    node_id: "MDQ6VXNlcjUzMzAzNzQ1",
    avatar_url: "https://avatars.githubusercontent.com/u/53303745?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kshitizJ",
    html_url: "https://github.com/kshitizJ",
    followers_url: "https://api.github.com/users/kshitizJ/followers",
    following_url: "https://api.github.com/users/kshitizJ/following{/other_user}",
    gists_url: "https://api.github.com/users/kshitizJ/gists{/gist_id}",
    starred_url: "https://api.github.com/users/kshitizJ/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/kshitizJ/subscriptions",
    organizations_url: "https://api.github.com/users/kshitizJ/orgs",
    repos_url: "https://api.github.com/users/kshitizJ/repos",
    events_url: "https://api.github.com/users/kshitizJ/events{/privacy}",
    received_events_url: "https://api.github.com/users/kshitizJ/received_events",
    type: "User",
    site_admin: false,
    name: "Kshitiz Jain",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 9,
    public_gists: 0,
    followers: 4,
    following: 7,
    created_at: "2019-07-25T12:44:17Z",
    updated_at: "2021-07-16T17:47:49Z"
};
